### ISSUE TITLE
Documentation full example

### ISSUE THREAD

**Issue by diederikproot** [gperl27/gatsby-styled-components-dark-mode#1]
Hi, I have some errors when I execute my "gatsby develop" command.

**1) Following the full example (in de readme) the ColorPalette object uses "=" instead of ":".** 

const ColorPalette = {
  lightShades = "242, 242, 241",
  lightAccent = "139, 142, 149",
  mainBrand = "140, 100, 88",
  darkAccent = "133, 129, 137",
  darkShades = "32, 30, 32",

  success = "95, 153, 81",
  warning = "221, 136, 25",
  error = "244, 67, 54",
}

**2) the export keyword is causing an error when I try to "require" the lightTheme and darkTheme object in the gatsby-config.js file.**

This is the error I get:

error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

  Error: C:\Users\name\Documents\GitHub\project\src\theme.js:32
  export const darkTheme = {
  ^^^^^^
  SyntaxError: Unexpected token export

Thank you for your work.

**Comment by gperl27** [comment]
Good catch, I'll update the readme. I ported my example from Typescript and I believe I had `ColorPalette` as an `enum`.


For #2, are you using Babel?

If not, try this:

```
const darkTheme = { main: "#aaa" }

module.exports = { darkTheme }
```

Thanks for for the help and checking out the project!

**Comment by diederikproot** [comment]
Thank you, that was the solution.
