### ISSUE TITLE
the project does not work properly in local (for contr.).

### ISSUE THREAD

**Issue by ahmetkuslular** [gperl27/gatsby-styled-components-dark-mode#16]
Hi greg,

I wanted to examine the project, but I could not test it in my local. I added the index.d.ts file to the main directory and resolved it, but it didn't work properly. I couldn't trigger toggle.

**gatsby-config.js**
```
 { 
      resolve: require.resolve('./gatsby-styled-components-dark-mode'),
      options: {
          light: { mainColor: 'brandyRose'},
          dark: { mainColor: 'manatee'},
      },
},
```

**./gatsby-styled-components-dark-mode -> index.d.ts**

```
import { ThemeManagerContext } from "./src";
export { ThemeManagerContext };
```

```
import { ThemeManagerContext } from "gatsby-styled-components-dark-mode"

export const Layout = (props) => {
  const themeContext = useContext(ThemeManagerContext)

  return (
    <div>
      <label>
        <input
          type="checkbox"
          onChange={() => themeContext.toggleDark()}
          checked={themeContext.isDark}
        />
        Dark mode
      </label>
    </div>
  )
}
```
I set it this way and import context in the example project but toggleDark is empty.

**Comment by gperl27** [comment]
Hey Ahmet,

Gatsby has some [docs](https://www.gatsbyjs.org/docs/creating-a-local-plugin/) for working with plugins locally. If you are still running into trouble, let me know.

Thanks for checking out the project!
