### ISSUE TITLE
Update readme on the Gatsby plugin website 

### ISSUE THREAD

**Issue by scorpiondev** [gperl27/gatsby-styled-components-dark-mode#19]
Not sure where the docs at https://www.gatsbyjs.org/packages/gatsby-styled-components-dark-mode/ are maintained, but they'll need to be updated to reflect the added system-mode functionality.

@gperl27: Happy to help with this if you point me the direction of where to make the changes 😊

**Comment by gperl27** [comment]
Appreciate it. All Gatsby does is point to our `readme.md`. 

Looking at that link, all the updates you added in the readme are there, so no need to do anything further unless you were looking to add even more docs.

**Comment by scorpiondev** [comment]
Whoops! Looks like I was looking at a cached version of that page - I see the updates now 😅

Happy to have this issue closed!
