### ISSUE TITLE
Light theme flash

### ISSUE THREAD

**Issue by Pirastrino** [gperl27/gatsby-styled-components-dark-mode#20]
Hi,

is there a way how to prevent the light theme flash when the dark theme is set by default on the page load, please?
Something like noflash.js [here](https://github.com/donavon/use-dark-mode#that-flash).

**Comment by gperl27** [comment]
Would you mind providing an example of your implementation?

We may need to use `useLayoutEffect` instead of `useEffect` when we manipulate the DOM.

**Comment by Pirastrino** [comment]
Hi I ended up with my own solution to this problem [here](https://github.com/Pirastrino/jam-maniacs) - `yarn install && cd app && yarn workspace app gatsby develop`, inspired by `gatsby-use-dark-mode` that toggles body class 'dark' and 'light'. 

First I wanted to use useDarkMode hook from use-dark-mode api that provides global context of the localStorage saved preferred theme and `gatsby-use-dark-mode` injects that `noflash.js` right after the body. It checks the localStorage first before the content is loaded so it loads with a correct theme - light or dark.

Then I tried your plugin, imported theme objects directly into `gatsby-config.ts`. However, I ended up with that flash when I use it with my GlobalContextProvider that provides and updates localStorage with a preferred theme. Later, I found out that it would probably work if I'd implemented my own script similar to that I currently have in `gatsby-ssr.tsx`.

So I think it would be nice if your plugin provides similar solution out of the box and injects some script to prevent that annoying flash. 

Feel free to check my repo but keep in mind that I am a self-thought dev ~1year so the code quality may not be the best 🙈

**Comment by LucasMallmann** [comment]
Well, the flash happens here https://github.com/gperl27/gatsby-styled-components-dark-mode/blob/cbc320b85960f84529e145e2e3fe8332e239f1f0/src/ThemeManager.tsx#L35 because this verifications happens only when the website is mounted. Well, IMO there would be no problem in removing this verification, since it is causing this flashing issue.

Also, the website context is different from the OS context. The user could choose which theme he'd like to see in the website.

**Comment by LucasMallmann** [comment]
Maybe the lib could provide a default theme property in the gatsby-config.js file.
