### ISSUE TITLE
NPM Error in Gatsby V3

### ISSUE THREAD

**Issue by emt-mocha** [gperl27/gatsby-styled-components-dark-mode#30]
Unable to install the said plugin on Gatsby V3.
The following error is a below:-

`
λ npm i gatsby-styled-components-dark-mode
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: dadgatsbyjswebsite@3.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from gatsby-styled-components-dark-mode@2.0.3
npm ERR! node_modules/gatsby-styled-components-dark-mode
npm ERR!   gatsby-styled-components-dark-mode@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ajaya\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ajaya\AppData\Local\npm-cache\_logs\2021-04-06T05_08_08_266Z-debug.log

`

**Comment by gperl27** [comment]
Thanks for raising this issue.

I just cloned a fresh [gatsby-starter](https://github.com/gatsbyjs/gatsby-starter-blog) which uses v3 and was able to install the package. Seeing some warnings about incorrect React versions, but still got through nonetheless.

However, until I push a fix out to upgrade React in this project, see if this command works:

`npm install --legacy-peer-deps`

**Comment by emt-mocha** [comment]
Thank you for the guide. 
The below command work with no errors.

`npm i gatsby-styled-components-dark-mode --legacy-peer-deps
`
