### ISSUE TITLE
Doesn't work with Gatsby v4

### ISSUE THREAD

**Issue by ilyagru** [gperl27/gatsby-styled-components-dark-mode#39]
After `gatsby develop` it can't load the app and throwing an error. Clean install and cache clean don't help. The plugin setup is identical to that which is described in the readme.

<img width="1512" alt="Screenshot 2022-01-07 at 12 15 48" src="https://user-images.githubusercontent.com/18074511/148536374-cc628185-36d8-4186-9c75-dacb7934b346.png">

```
"gatsby-styled-components-dark-mode": "^2.0.4",
"babel-plugin-styled-components": "^2.0.2",
"styled-components": "^5.3.3",
"gatsby-plugin-styled-components": "^5.4.0",
"gatsby": "^4.4.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

**Comment by Antonwy** [comment]
For me, deleting the browser cache worked.
