### ISSUE TITLE
Add option to set dark mode as default

### ISSUE THREAD

**Issue by BrunnerLivio** [gperl27/gatsby-styled-components-dark-mode#9]
Hi, I would like to set my dark theme as the default theme when entering the website.
The `gatsby-config.js` should allow setting the default value of "`ThemeManagerContext.isDark`"

For example

`gatsby-config.js`

```js
   {
      resolve: `gatsby-styled-components-dark-mode`,
      options: {
        light: require(`${__dirname}/src/theme.js`).lightTheme,
        dark: require(`${__dirname}/src/theme.js`).darkTheme,
        // The new option
        defaultIsDark: true,
      },
    },
```

**Comment by BrunnerLivio** [comment]
I'd be willing to contribute to this feature! Please let me know whether this fits your vision.

**Comment by gperl27** [comment]
Hi, this is a great idea!

Let's have the api try to mirror the theme manager's `props`:

```
{
    resolve: `gatsby-styled-components-dark-mode`,
    options: {
      light: require(`${__dirname}/src/theme.js`).lightTheme,
      dark: require(`${__dirname}/src/theme.js`).darkTheme,
      // The new option
      defaultThemeManagerProps: {
          isDark: true
      }
    },
},
```

I almost wonder though if the approach is too imperative. A more declarative implementation could expose a parameter to `toggleDark` and the consumer can call that when their application mounts. Something like:

```
function App() {
  React.useEffect(() => {
    toggleDark(true)
  }, [])

  return (
      <ComponentsHere />
  )
}
```

What do you think?

Definitely feel free to open up a PR. And thanks for checking out the project!

**Comment by BrunnerLivio** [comment]
> A more declarative implementation could expose a parameter to toggleDark

Fine for me too!
